### DISCUSSION TITLE
How to set a env value as the value for another env?

### DISCUSSION THREAD

**Discussion by mrmartineau** [FranzDiebold/github-env-vars-action#40] [Q&A] [answered]
I'd like to use one of the provided env vars (e.g. `CI_SHA_SHORT`) as a value for a new env var in a subsequent step, but I can't seem to figure out how to do it.

```yaml
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: FranzDiebold/github-env-vars-action@v2
      - name: Install dependencies
        run: yarn --prefer-offline
      - name: Deploy previews
        id: deploy_firebase_hosting_channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DFX_STAGING }}'
          projectId: dfx-staging
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
          VITE_API_BASE_PATH: '${{ secrets.API_BASE_PATH_STAGING }}'
          VITE_GIT_SHA: $CI_SHA_SHORT
          VITE_GIT_REF: $CI_REF_NAME
```

The 2 env vars that I'd like to be set are `VITE_GIT_SHA` and `VITE_GIT_REF` (at the bottom). I think I have tried 20 different ways to achieve this (including the same way that `secrets` var is used) but none of them seem to work.

Can you help?

**Comment by FranzDiebold** [comment, marked as answer]
Hi @mrmartineau,

I am happy to help! 🚀 

What about the following?

```yaml
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      ...
      - name: Deploy previews
        ...
        env:
          ...
          VITE_GIT_SHA: "${{ env.CI_SHA_SHORT }}"
          VITE_GIT_REF: "${{ env.CI_REF_NAME }}"
```

You can see the results on [this](https://github.com/FranzDiebold/github-env-vars-action/blob/demo/demo-branch-for-pull-request/.github/workflows/demo.yml#L58-L59) branch with actions output [here](https://github.com/FranzDiebold/github-env-vars-action/runs/2582747768).

Does this solve your problem?
