### ISSUE TITLE
cannot get correct short sha for pull requests

### ISSUE THREAD

**Issue by masterkain** [FranzDiebold/github-env-vars-action#30]
I have a workflow based on this:

```
on:
  pull_request:
    types: [opened, reopened, closed]

    steps:
      - name: GitHub Environment Variables Action
        uses: FranzDiebold/github-env-vars-action@v2.1.0

```

and I'm using `SHA8: ${{ env.CI_SHA_SHORT }} in my job`

however the resulting SHA is not something that I can use, it does not correspond to anything in the repo.
